version: "3.8"
services:
  weather-alert:
    build:
      context: . # Dockerfile이 있는 현재 디렉토리를 빌드
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs # 로그를 외부로 마운트 (선택사항)
      - ./data:/app/data # 데이터 폴더 마운트 (필요 시)
    ports:
      - "3001:3001" # Flask 또는 애플리케이션 포트를 매핑
    environment:
      - TZ=Asia/Seoul # 시간대 설정
    restart: always # 컨테이너가 종료되면 자동 재시작
